import io
import hashlib
import numpy as np
import torch
from PIL import Image, ImageChops, ImageEnhance
from transformers import AutoImageProcessor, AutoModelForImageClassification

class ImageForensicDetector:
    def __init__(self):
        self.model_name = "dima806/deepfake_vs_real_image_detection"
        self.processor = AutoImageProcessor.from_pretrained(self.model_name)
        self.model = AutoModelForImageClassification.from_pretrained(self.model_name)
        self.model.eval()

    def generate_ela(self, original_img: Image.Image, quality: int = 90) -> tuple[Image.Image, float]:
        """Error Level Analysis to locate JPEG compression grid discrepancies."""
        rgb_img = original_img.convert("RGB")
        buffer = io.BytesIO()
        rgb_img.save(buffer, "JPEG", quality=quality)
        buffer.seek(0)
        compressed_img = Image.open(buffer)

        diff = ImageChops.difference(rgb_img, compressed_img)
        extrema = diff.getextrema()
        max_diff = max([ex[1] for ex in extrema])
        scale = 255.0 / max_diff if max_diff != 0 else 1.0
        ela_img = ImageEnhance.Brightness(diff).enhance(scale)

        diff_arr = np.array(diff, dtype=np.float32)
        mean_anomaly_score = float(np.mean(diff_arr))
        return ela_img, mean_anomaly_score

    def compute_fft_spectrum(self, original_img: Image.Image) -> tuple[Image.Image, float]:
        """
        2D Fast Fourier Transform (FFT) Frequency Decomposition.
        Exposes periodic grid artifacts generated by GAN/Diffusion deconvolution layers.
        """
        gray = original_img.convert("L")
        img_arr = np.array(gray, dtype=np.float32)
        h, w = img_arr.shape

        # 2D Discrete Fourier Transform & shift zero frequency component to center
        f_transform = np.fft.fft2(img_arr)
        f_shift = np.fft.fftshift(f_transform)

        # Log-scaled magnitude spectrum
        magnitude_spectrum = 20 * np.log(np.abs(f_shift) + 1e-9)

        # Normalize to 8-bit dynamic range [0, 255]
        norm_spectrum = (magnitude_spectrum - np.min(magnitude_spectrum)) / (np.ptp(magnitude_spectrum) + 1e-9) * 255.0
        spectrum_img = Image.fromarray(norm_spectrum.astype(np.uint8))

        # Center mask aligned directly to array shape (height, width)
        cy, cx = h // 2, w // 2
        r = min(h, w) // 4
        y, x = np.ogrid[:h, :w]
        mask = ((y - cy)**2 + (x - cx)**2) > r**2
        hf_energy_ratio = float(np.mean(np.abs(f_shift)[mask]))

        return spectrum_img, hf_energy_ratio

    def classify_deepfake(self, image: Image.Image) -> dict:
        """Inference over fine-tuned Vision Transformer architecture."""
        inputs = self.processor(images=image.convert("RGB"), return_tensors="pt")
        with torch.no_grad():
            outputs = self.model(**inputs)
            probs = torch.nn.functional.softmax(outputs.logits, dim=-1)[0]

        id2label = self.model.config.id2label
        results = {id2label[i].lower(): float(probs[i]) for i in range(len(probs))}
        fake_prob = results.get("fake", 0.0)

        return {
            "fake_probability": fake_prob,
            "verdict": "Likely AI-Generated / Spliced" if fake_prob > 0.55 else "Likely Authentic",
            "confidence": max(fake_prob, 1 - fake_prob) * 100
        }
