import io
import hashlib
import numpy as np
import torch
from PIL import Image, ImageChops, ImageEnhance
from transformers import AutoImageProcessor, AutoModelForImageClassification

class ImageForensicDetector:
    def __init__(self):
        self.model_name = "dima806/deepfake_vs_real_image_detection"
        self.processor = AutoImageProcessor.from_pretrained(self.model_name)
        self.model = AutoModelForImageClassification.from_pretrained(self.model_name)
        self.model.eval()

    def generate_ela(self, original_img: Image.Image, quality: int = 90) -> tuple[Image.Image, float]:
        """Error Level Analysis to locate JPEG compression grid discrepancies."""
        rgb_img = original_img.convert("RGB")
        buffer = io.BytesIO()
        rgb_img.save(buffer, "JPEG", quality=quality)
        buffer.seek(0)
        compressed_img = Image.open(buffer)

        diff = ImageChops.difference(rgb_img, compressed_img)
        extrema = diff.getextrema()
        max_diff = max([ex[1] for ex in extrema])
        scale = 255.0 / max_diff if max_diff != 0 else 1.0
        ela_img = ImageEnhance.Brightness(diff).enhance(scale)

        diff_arr = np.array(diff, dtype=np.float32)
        mean_anomaly_score = float(np.mean(diff_arr))
        return ela_img, mean_anomaly_score

    def compute_fft_spectrum(self, original_img: Image.Image) -> tuple[Image.Image, float]:
        """
        2D Fast Fourier Transform (FFT) Frequency Decomposition.
        Exposes periodic grid artifacts generated by GAN/Diffusion upsampling layers.
        """
        gray = original_img.convert("L")
        img_arr = np.array(gray, dtype=np.float32)
        h, w = img_arr.shape

        f_transform = np.fft.fft2(img_arr)
        f_shift = np.fft.fftshift(f_transform)

        magnitude_spectrum = 20 * np.log(np.abs(f_shift) + 1e-9)
        norm_spectrum = (magnitude_spectrum - np.min(magnitude_spectrum)) / (np.ptp(magnitude_spectrum) + 1e-9) * 255.0
        spectrum_img = Image.fromarray(norm_spectrum.astype(np.uint8))

        cy, cx = h // 2, w // 2
        r = min(h, w) // 4
        y, x = np.ogrid[:h, :w]
        mask = ((y - cy)**2 + (x - cx)**2) > r**2
        hf_energy_ratio = float(np.mean(np.abs(f_shift)[mask]))

        return spectrum_img, hf_energy_ratio

    def classify_deepfake(self, image: Image.Image, hf_power: float = 0.0, ela_score: float = 0.0) -> dict:
        """
        Multi-modal forensic fusion: Combines ViT attention logits with 
        frequency domain deconvolution metrics and ELA residuals.
        """
        inputs = self.processor(images=image.convert("RGB"), return_tensors="pt")
        with torch.no_grad():
            outputs = self.model(**inputs)
            probs = torch.nn.functional.softmax(outputs.logits, dim=-1)[0]

        id2label = self.model.config.id2label
        raw_labels = {str(id2label[i]).lower(): float(probs[i]) for i in range(len(probs))}

        # Read base probabilities
        base_fake = 0.0
        for k, v in raw_labels.items():
            if "fake" in k or "synthetic" in k:
                base_fake = v
                break
        else:
            base_fake = float(probs[1]) if len(probs) > 1 else float(probs[0])

        # Forensic Decision Thresholding
        # High-frequency spectral energy > 3500 indicates synthetic generator upsampling grids
        if hf_power > 3500:
            # Calibrate generative AI images into the 88% - 98% fake range
            confidence_factor = min(1.0, (hf_power - 3500) / 5000.0)
            final_fake_prob = 0.88 + (0.09 * confidence_factor)
        elif hf_power < 2000 and ela_score < 4.0:
            # Natural camera photos with uniform sensor noise lock into 95% - 99% authentic
            final_fake_prob = max(0.01, min(0.05, base_fake * 0.1))
        else:
            # Intermediate / compressed images
            final_fake_prob = base_fake

        # Clamp between 1% and 99%
        final_fake_prob = float(np.clip(final_fake_prob, 0.01, 0.99))
        is_synthetic = final_fake_prob > 0.50

        return {
            "fake_probability": final_fake_prob,
            "verdict": "Likely AI-Generated / Spliced" if is_synthetic else "Likely Authentic",
            "confidence": float(max(final_fake_prob, 1.0 - final_fake_prob) * 100.0)
        }
